"use client";

import React, { useState } from "react";
import { slugify } from "@/lib/stringutils";

export interface Statute {
  id?: number;
  citation: string;
  title: string;
  slug: string;
  summary: string;
  legal_text: string;
  jurisdiction: 'Federal' | 'State' | 'Local';
  jurisdiction_body: string;
  seo_description?: string;
  seo_keywords?: string;
  official_website_url?: string;
  categories?: string[];
  tags?: string[];
}

interface Taxonomy { id: number; name: string; type: 'category' | 'tag'; slug: string; }

interface StatuteFormProps {
  initialData?: Statute | null;
  taxonomies: Taxonomy[];
  onSave: (data: Statute) => Promise<void>;
}

// Helper to generate a URL‑friendly slug from a statute citation
const generateStatuteSlug = (citation: string): string => {
  return citation
    .toLowerCase()
    .trim()
    .replace(/[.\s]+/g, '-')   // replace dots and spaces with hyphens
    .replace(/[^a-z0-9-]/g, ''); // remove everything except letters, numbers, hyphens
};

export default function StatuteForm({ initialData, taxonomies, onSave }: StatuteFormProps) {
  const emptyState: Statute = {
    citation: "", title: "", slug: "", summary: "", legal_text: "",
    jurisdiction: 'Federal',
    jurisdiction_body: "",
    seo_description: "", seo_keywords: "", official_website_url: "",
    categories: [""], tags: [""]
  };

  const [formData, setFormData] = useState<Statute>(() => {
    if (!initialData) return emptyState;
    return {
      ...emptyState,
      ...initialData,
      categories: initialData.categories?.length ? initialData.categories : [""],
      tags: initialData.tags?.length ? initialData.tags : [""],
    };
  });

  const [isPending, setIsPending] = useState(false);

  // Title change: Only auto-slug if there is NO citation yet.
  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const title = e.target.value;
    if (!formData.citation) {
      setFormData(prev => ({ ...prev, title, slug: slugify(title) }));
    } else {
      setFormData(prev => ({ ...prev, title }));
    }
  };

  // Citation change: This is the MASTER slug driver.
  const handleCitationChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const citation = e.target.value;
    const autoSlug = generateStatuteSlug(citation);
    
    // Logic: Always overwrite the slug with the citation-slug UNLESS the user 
    // has manually changed the slug to something custom already.
    const isNewRecord = !initialData?.id;
    const isSlugCurrentlyAutoGenerated = formData.slug === generateStatuteSlug(formData.citation) || formData.slug === slugify(formData.title);

    if (isNewRecord || isSlugCurrentlyAutoGenerated) {
      setFormData(prev => ({ ...prev, citation, slug: autoSlug }));
    } else {
      setFormData(prev => ({ ...prev, citation }));
    }
  };

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData(prev => ({ ...prev, slug: e.target.value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsPending(true);
    await onSave(formData);
    setIsPending(false);
  };

  const inputClass = "w-full bg-slate-900 border border-slate-800 p-3 text-sm text-white focus:border-blue-500 outline-none transition-all";
  const labelClass = "block text-[9px] text-slate-500 uppercase font-black mb-1";

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-1 mb-4">
        <label className="text-[9px] text-slate-500 uppercase font-black tracking-widest">System_Status</label>
        <div className="flex items-center gap-2">
          <div className={`w-2 h-2 rounded-full ${isPending ? 'bg-yellow-500 animate-ping' : 'bg-emerald-500'}`} />
          <span className="text-[10px] text-white font-bold uppercase tracking-widest">
            {isPending ? 'Processing_Request...' : 'Ready'}
          </span>
        </div>
      </div>

      <div>
        <label className={labelClass}>Statute_Title</label>
        <input type="text" value={formData.title} onChange={handleTitleChange} className={inputClass} required />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className={labelClass}>Legal_Citation</label>
          <input type="text" value={formData.citation} onChange={handleCitationChange} className={inputClass} required />
        </div>
        <div>
          <label className={labelClass}>URL_Slug</label>
          <input type="text" value={formData.slug} onChange={handleSlugChange} className={`${inputClass} text-blue-400 font-mono`} required />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className={labelClass}>Jurisdiction_Level</label>
          <select
            value={formData.jurisdiction}
            onChange={(e) => setFormData({ ...formData, jurisdiction: e.target.value as Statute['jurisdiction'] })}
            className={`${inputClass} uppercase font-bold text-blue-400`}
          >
            <option value="Federal">Federal</option>
            <option value="State">State</option>
            <option value="Local">Local</option>
          </select>
        </div>
        <div>
          <label className={labelClass}>Governing_Body</label>
          <input
            type="text"
            placeholder="e.g. Michigan / Redford / U.S."
            value={formData.jurisdiction_body || ""}
            onChange={(e) => setFormData({ ...formData, jurisdiction_body: e.target.value })}
            className={inputClass}
          />
        </div>
      </div>

      <div>
        <label className={labelClass}>Executive_Summary</label>
        <textarea value={formData.summary} onChange={(e) => setFormData({ ...formData, summary: e.target.value })} className={`${inputClass} h-20 resize-none`} />
      </div>

      <div>
        <label className={labelClass}>Full_Legal_Text</label>
        <textarea value={formData.legal_text} onChange={(e) => setFormData({ ...formData, legal_text: e.target.value })} className={`${inputClass} h-40 resize-none text-[10px] leading-relaxed`} />
      </div>

      <div className="border-t border-slate-900 pt-6 mt-6 space-y-6">
        <h4 className="text-[10px] text-blue-500 font-black uppercase tracking-widest">Taxonomy & Links</h4>
        
        <div>
          <label className={labelClass}>Categories</label>
          {formData.categories?.map((c, i) => (
            <div key={`cat-${i}`} className="flex gap-2 mb-2">
              <select value={c} onChange={e => {
                const newCats = [...(formData.categories || [])];
                newCats[i] = e.target.value;
                setFormData({ ...formData, categories: newCats });
              }} className={`${inputClass} uppercase font-bold`}>
                <option value="">-- SELECT CATEGORY --</option>
                {taxonomies.filter(t => t.type === 'category').map(t => (
                  <option key={t.id} value={String(t.slug)}>{t.name}</option>
                ))}
              </select>
              <button type="button" onClick={() => setFormData({ ...formData, categories: formData.categories?.filter((_, idx) => idx !== i) })} className="px-4 bg-red-950/40 border border-red-900 text-red-500 hover:bg-red-600 hover:text-white font-bold transition-all">[X]</button>
            </div>
          ))}
          <button type="button" onClick={() => setFormData({ ...formData, categories: [...(formData.categories || []), ""] })} className="text-[9px] text-[#4A90E2] font-bold uppercase hover:underline">+ Add Additional Category</button>
        </div>

        <div>
          <label className={labelClass}>Tags</label>
          {formData.tags?.map((t, i) => (
            <div key={`tag-${i}`} className="flex gap-2 mb-2">
              <select value={t} onChange={e => {
                const newTags = [...(formData.tags || [])];
                newTags[i] = e.target.value;
                setFormData({ ...formData, tags: newTags });
              }} className={`${inputClass} uppercase font-bold`}>
                <option value="">-- SELECT TAG --</option>
                {taxonomies.filter(t => t.type === 'tag').map(tax => (
                  <option key={tax.id} value={String(tax.slug)}>{tax.name}</option>
                ))}
              </select>
              <button type="button" onClick={() => setFormData({ ...formData, tags: formData.tags?.filter((_, idx) => idx !== i) })} className="px-4 bg-red-950/40 border border-red-900 text-red-500 hover:bg-red-600 hover:text-white font-bold transition-all">[X]</button>
            </div>
          ))}
          <button type="button" onClick={() => setFormData({ ...formData, tags: [...(formData.tags || []), ""] })} className="text-[9px] text-[#4A90E2] font-bold uppercase hover:underline">+ Add Additional Tag</button>
        </div>

        <div>
          <label className={labelClass}>Official Website URL</label>
          <input type="url" value={formData.official_website_url || ""} onChange={(e) => setFormData({ ...formData, official_website_url: e.target.value })} className={`${inputClass} text-blue-400 font-mono`} placeholder="https://..." />
        </div>

        <div>
          <label className={labelClass}>SEO_Description</label>
          <textarea value={formData.seo_description || ""} onChange={(e) => setFormData({ ...formData, seo_description: e.target.value })} className={`${inputClass} h-16 resize-none`} />
        </div>

        <div>
          <label className={labelClass}>SEO_Keywords</label>
          <input type="text" value={formData.seo_keywords || ""} onChange={(e) => setFormData({ ...formData, seo_keywords: e.target.value })} className={inputClass} />
        </div>
      </div>

      <button type="submit" disabled={isPending} className={`w-full mt-6 py-4 text-[11px] font-black uppercase tracking-[0.3em] transition-all border ${isPending ? 'bg-slate-900 border-slate-800 text-slate-600 cursor-not-allowed' : 'bg-blue-600 text-white border-blue-400 hover:bg-blue-500 active:scale-[0.98]'}`}>
        {initialData?.id ? '[ Execute_Update ]' : '[ Commit_to_Registry ]'}
      </button>
    </form>
  );
}